spring.application.name=thymeleaf-sample-application
server.port=9000

spring.thymeleaf.cache=false

# -----------
# -- i18n --
# -----------
#spring.messages.basename=messages,texts
#spring.messages.encoding=UTF-8

# -------------
# -- Aspects --
# -------------
aspect.page-controllers.pointcut=within(com.mpodda.thymeleaf_sample.controllers.pages..*)

# --------------
# -- Database --
# --------------
#spring.datasource.url=jdbc:postgresql://localhost:5433/samples
spring.datasource.jdbc-url=jdbc:postgresql://localhost:5433/samples
spring.datasource.username=sample
spring.datasource.password=sample
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update



# -----------------------------------------------
# -- Spring Session JDBC Connection Properites --
# -----------------------------------------------

#app.session.datasource.jdbc-url=jdbc:postgresql://localhost:5433/samples_sessions
app.session.datasource.url=jdbc:postgresql://localhost:5433/samples_sessions
app.session.datasource.username=sample_session
app.session.datasource.password=sample
app.session.datasource.driver-class-name=org.postgresql.Driver

#spring.session.jdbc.initialize-schema=always
#spring.session.jdbc.table-name=thysa_spring_session
#spring.session.jdbc.flush-mode=on_save
#spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-postgresql.sql


# -------------------------------------------
# -- Custom Application Parameter          --
# -- "thysa": Thymeleaf Sample Application -- 
# -------------------------------------------

thysa.page-size = 5
thysa.max-number-of-pages = 10
thysa.number-of-limits-pages = 3


#logging.level.org.springframework.boot.context.properties=TRACE
