spring.application.name=thymeleaf-sample-application
server.port=9000

spring.thymeleaf.cache=false

# --------------
# -- Database --
# --------------
spring.datasource.url=jdbc:postgresql://localhost:5433/samples
spring.datasource.username=sample
spring.datasource.password=sample

spring.jpa.hibernate.ddl-auto=update


# -----------------------------------------------
# -- Spring Session JDBC Connection Properites --
# -----------------------------------------------
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.table-name=SPRING_SESSION
spring.session.jdbc.flush-mode=on_save

# -----------------------------------------
# -- Custom Application Parameter        --
# -- "tsa": Thymeleaf Sample Application -- 
# -----------------------------------------

tsa.page-size = 5
tsa.max-number-of-pages = 10
tsa.number-of-limits-pages = 3