spring.application.name=thymeleaf-sample-application
server.port=9000

spring.thymeleaf.cache=false

# --------------
# -- Database --
# --------------
spring.datasource.url=jdbc:postgresql://localhost:5433/samples
spring.datasource.username=sample
spring.datasource.password=sample

spring.jpa.hibernate.ddl-auto=update


# -----------------------------------------------
# -- Spring Session JDBC Connection Properites --
# -----------------------------------------------
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.table-name=SPRING_SESSION
spring.session.jdbc.flush-mode=on_save

